version: "3"

services:
  cypherapp-mempool:
    # environment:
      # - "TRACING=1"
      # - "CYPHERNODE_URL=https://gatekeeper:${GATEKEEPER_PORT}"
    image: cypherapp-mempool:v0.0.1 
    volumes:
      - "$GATEKEEPER_DATAPATH/certs/cert.pem:/data/cert.pem"
      - "$GATEKEEPER_DATAPATH/keys.properties:/data/keys.properties"
      - "$APP_SCRIPT_PATH/config.toml:/data/config.toml"
      - "$GATEKEEPER_DATAPATH/htpasswd:/htpasswd/htpasswd"
    networks:
      - cyphernodenet
    restart: always
    labels:
      - "traefik.docker.network=cyphernodenet"
      - "traefik.frontend.rule=PathPrefixStrip:/mempool"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.frontend.auth.basic.usersFile=/htpasswd/htpasswd"
networks:
  cyphernodenet:
    external: true